version: "2"
checks:
  argument-count:
    enabled: true
  method-complexity:
    enabled: true

plugins:
  eslint:
    enabled: true
  duplication:
    enabled: true
  fixme:
    enabled: true
  test-coverage:
    enabled: true

ratings:
  paths:
    - "**.js"
    - "**.ts"
exclude_patterns:
  - "node_modules/"
  - "dist/"
