spring:
  application:
    name: ACME Games
  datasource:
    url: jdbc:h2:mem:games
    username: FLM
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
