spring:
  application:
    name: ACME Games
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:games
    username: FLM
    password: 1234


  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
    

  sql:
    init:
      mode: always
      data-locations: classpath*:./insert.sql


  h2:
    console:
      enabled: true
      path: /h2-console

