spring:
  application:
    name: ACME Games
  datasource:
    url: jdbc:h2:mem:games
    username: FLM
    password: 1234
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
  h2:
    console:
      enabled: true
      path: /h2-console
