# .github/workflows/ci-java.yml
name: CI (Qlty + Java)

on:
  workflow_dispatch:
  push:
    branches: ["**"]
  pull_request:
    branches: 
      - main
      - develop

permissions:
  contents: read
  id-token: write # Required for OIDC

jobs:
  qlty-check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instalar Qlty CLI
      - name: Instalar Qlty CLI
        run: curl -s https://qlty.sh/install.sh | bash

      # Rodar análise de qualidade com base no qlty.toml
      - name: Rodar análise Qlty
        run: qlty check

  test-and-coverage:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      # Instalar JDK
      - uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 17

      # Rodar testes e gerar relatório JaCoCo
      - name: Rodar testes com Maven e gerar cobertura
        run: mvn clean test jacoco:report

      # Enviar cobertura para o Qlty
      - uses: qltysh/qlty-action/coverage@v2
        with:
          oidc: true
          files: target/site/jacoco/jacoco.xml
